### ISSUE TITLE
Applicable Model Years

### ISSUE THREAD

**Issue by Wantland1** [flyboy013/DEF_Sensor_Emulator_Firmware#4]
I have researched and can not seem to find how long there has been this sensor problem. Anyone know what year it became an issue? Did earlier units have same def sensor as current units. Four pin plug vs three??
Thank you

**Comment by flyboy013** [comment]
The three wire plugs would be for an analog level sensor and would not be subject to the same issue.  Those three wires are for 12V, Ground, and sensor output.

My coach is a 2018 and failed in February of 2021.  I believe folks have reported failures in coaches a few years older.  IRV2 has lots of owner comments that should help to better pinpoint the timeframe.
